<a href="https://colab.research.google.com/github/studian/study_pytorch/blob/main/1%EA%B0%95_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EC%9E%85%EB%AC%B8_%ED%95%84%EC%88%98_%EC%98%81%EC%83%81(%ED%85%90%EC%84%9C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5,4)
print(x)

tensor([[4.0968e-36, 0.0000e+00, 7.0065e-44, 6.7262e-44],
        [6.3058e-44, 6.8664e-44, 7.0065e-44, 6.3058e-44],
        [6.8664e-44, 7.1466e-44, 1.1771e-43, 6.8664e-44],
        [6.7262e-44, 8.1275e-44, 7.1466e-44, 7.5670e-44],
        [8.1275e-44, 6.8664e-44, 6.8664e-44, 6.4460e-44]])


In [3]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
l = [13,4]
r = np.array([[4,56,7]])

In [5]:
torch.tensor(l)

tensor([13,  4])

In [6]:
torch.tensor(r)

tensor([[ 4, 56,  7]])

In [7]:
x.size()

torch.Size([5, 4])

In [8]:
type(x)

torch.Tensor

In [9]:
x= torch.rand(2,2)
y= torch.rand(2,2)
print(x)
print(y)

tensor([[0.1081, 0.8075],
        [0.3392, 0.3508]])
tensor([[0.8971, 0.1295],
        [0.1048, 0.9496]])


In [10]:
x+y

tensor([[1.0052, 0.9370],
        [0.4439, 1.3004]])

In [11]:
torch.add(x,y)


tensor([[1.0052, 0.9370],
        [0.4439, 1.3004]])

In [12]:
y.add(x)

tensor([[1.0052, 0.9370],
        [0.4439, 1.3004]])

In [13]:
y

tensor([[0.8971, 0.1295],
        [0.1048, 0.9496]])

In [14]:
y.add_(x)

tensor([[1.0052, 0.9370],
        [0.4439, 1.3004]])

In [15]:
y

tensor([[1.0052, 0.9370],
        [0.4439, 1.3004]])

In [16]:
y[:,1]

tensor([0.9370, 1.3004])

In [17]:
y[1,:]

tensor([0.4439, 1.3004])

In [18]:
x = torch.rand(8,8)
print(x)
# 2차원 벡터 생성.. 랜덤으로

tensor([[0.8615, 0.2196, 0.1513, 0.4157, 0.0716, 0.0852, 0.0296, 0.4423],
        [0.8919, 0.0355, 0.2560, 0.8386, 0.8192, 0.0467, 0.1905, 0.7797],
        [0.6097, 0.6609, 0.9235, 0.7643, 0.7146, 0.4733, 0.2128, 0.4901],
        [0.4317, 0.1459, 0.7785, 0.8602, 0.8362, 0.0707, 0.5935, 0.2376],
        [0.2913, 0.4737, 0.6523, 0.2639, 0.1501, 0.6722, 0.3817, 0.1189],
        [0.3150, 0.2867, 0.1704, 0.9746, 0.0235, 0.5970, 0.3980, 0.1984],
        [0.7574, 0.9570, 0.3150, 0.4169, 0.7866, 0.2734, 0.0082, 0.9438],
        [0.9365, 0.8160, 0.3071, 0.9257, 0.9921, 0.5787, 0.2950, 0.9767]])


In [19]:
x.view(64) # CNN -> 플래튼 할때 사용
# 2차원 벡터를 1차원 벡터로 바꿈,

tensor([0.8615, 0.2196, 0.1513, 0.4157, 0.0716, 0.0852, 0.0296, 0.4423, 0.8919,
        0.0355, 0.2560, 0.8386, 0.8192, 0.0467, 0.1905, 0.7797, 0.6097, 0.6609,
        0.9235, 0.7643, 0.7146, 0.4733, 0.2128, 0.4901, 0.4317, 0.1459, 0.7785,
        0.8602, 0.8362, 0.0707, 0.5935, 0.2376, 0.2913, 0.4737, 0.6523, 0.2639,
        0.1501, 0.6722, 0.3817, 0.1189, 0.3150, 0.2867, 0.1704, 0.9746, 0.0235,
        0.5970, 0.3980, 0.1984, 0.7574, 0.9570, 0.3150, 0.4169, 0.7866, 0.2734,
        0.0082, 0.9438, 0.9365, 0.8160, 0.3071, 0.9257, 0.9921, 0.5787, 0.2950,
        0.9767])

In [20]:
x.view(4,16)
# 8x8 행렬을 --> 4x16 행렬로 바꿈

tensor([[0.8615, 0.2196, 0.1513, 0.4157, 0.0716, 0.0852, 0.0296, 0.4423, 0.8919,
         0.0355, 0.2560, 0.8386, 0.8192, 0.0467, 0.1905, 0.7797],
        [0.6097, 0.6609, 0.9235, 0.7643, 0.7146, 0.4733, 0.2128, 0.4901, 0.4317,
         0.1459, 0.7785, 0.8602, 0.8362, 0.0707, 0.5935, 0.2376],
        [0.2913, 0.4737, 0.6523, 0.2639, 0.1501, 0.6722, 0.3817, 0.1189, 0.3150,
         0.2867, 0.1704, 0.9746, 0.0235, 0.5970, 0.3980, 0.1984],
        [0.7574, 0.9570, 0.3150, 0.4169, 0.7866, 0.2734, 0.0082, 0.9438, 0.9365,
         0.8160, 0.3071, 0.9257, 0.9921, 0.5787, 0.2950, 0.9767]])

In [21]:
x.view(-1,16)
# 8x8 행렬을 --> 4x16 행렬로 바꿈

tensor([[0.8615, 0.2196, 0.1513, 0.4157, 0.0716, 0.0852, 0.0296, 0.4423, 0.8919,
         0.0355, 0.2560, 0.8386, 0.8192, 0.0467, 0.1905, 0.7797],
        [0.6097, 0.6609, 0.9235, 0.7643, 0.7146, 0.4733, 0.2128, 0.4901, 0.4317,
         0.1459, 0.7785, 0.8602, 0.8362, 0.0707, 0.5935, 0.2376],
        [0.2913, 0.4737, 0.6523, 0.2639, 0.1501, 0.6722, 0.3817, 0.1189, 0.3150,
         0.2867, 0.1704, 0.9746, 0.0235, 0.5970, 0.3980, 0.1984],
        [0.7574, 0.9570, 0.3150, 0.4169, 0.7866, 0.2734, 0.0082, 0.9438, 0.9365,
         0.8160, 0.3071, 0.9257, 0.9921, 0.5787, 0.2950, 0.9767]])

In [22]:
x.view(-1,4,4)
# 8x8 행렬을 --> 1x4x4 행렬로 바꿈


tensor([[[0.8615, 0.2196, 0.1513, 0.4157],
         [0.0716, 0.0852, 0.0296, 0.4423],
         [0.8919, 0.0355, 0.2560, 0.8386],
         [0.8192, 0.0467, 0.1905, 0.7797]],

        [[0.6097, 0.6609, 0.9235, 0.7643],
         [0.7146, 0.4733, 0.2128, 0.4901],
         [0.4317, 0.1459, 0.7785, 0.8602],
         [0.8362, 0.0707, 0.5935, 0.2376]],

        [[0.2913, 0.4737, 0.6523, 0.2639],
         [0.1501, 0.6722, 0.3817, 0.1189],
         [0.3150, 0.2867, 0.1704, 0.9746],
         [0.0235, 0.5970, 0.3980, 0.1984]],

        [[0.7574, 0.9570, 0.3150, 0.4169],
         [0.7866, 0.2734, 0.0082, 0.9438],
         [0.9365, 0.8160, 0.3071, 0.9257],
         [0.9921, 0.5787, 0.2950, 0.9767]]])

In [23]:
# tensor를 numpy로 바꾸기
y = x.numpy()
print(y)
type(y)

[[0.8615257  0.21959221 0.15130848 0.41574132 0.0715515  0.08523792
  0.0295648  0.44233042]
 [0.8919014  0.03550529 0.25597382 0.83862793 0.8191854  0.0466879
  0.19050407 0.7797304 ]
 [0.6096645  0.6608696  0.9235146  0.7642912  0.7145978  0.47326988
  0.21283096 0.49014813]
 [0.43174106 0.14590049 0.7784941  0.8601613  0.8362388  0.07066435
  0.59353876 0.23761135]
 [0.29125702 0.4737029  0.6522568  0.26394677 0.15010393 0.67222315
  0.3816834  0.11888593]
 [0.31498605 0.2866847  0.17039466 0.9746177  0.02346039 0.59696203
  0.398004   0.1983661 ]
 [0.75739086 0.9569682  0.31502688 0.41691983 0.7866424  0.27344877
  0.00816131 0.94375116]
 [0.936468   0.8159814  0.3071469  0.9257409  0.9921252  0.57871276
  0.29502028 0.97674936]]


numpy.ndarray

In [24]:
# item : 원소가 1개일때만 사용가능, 스칼라값 ==> loss 계산할때 대표 loss값을 직접뽑아내고 싶을때 사용하면 됨
x = torch.ones(1)

In [25]:
x

tensor([1.])

In [26]:
x.item()

1.0