<a href="https://colab.research.google.com/github/studian/study_pytorch/blob/main/1%EA%B0%95_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EC%9E%85%EB%AC%B8_%ED%95%84%EC%88%98_%EC%98%81%EC%83%81(%ED%85%90%EC%84%9C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [5]:
x = torch.empty(5,4)
print(x)

tensor([[3.7597e-35, 0.0000e+00, 7.0065e-44, 6.7262e-44],
        [6.3058e-44, 6.8664e-44, 7.0065e-44, 6.3058e-44],
        [6.8664e-44, 7.1466e-44, 1.1771e-43, 6.8664e-44],
        [6.7262e-44, 8.1275e-44, 6.8664e-44, 7.8473e-44],
        [8.1275e-44, 6.8664e-44, 6.8664e-44, 6.4460e-44]])


In [6]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
l = [13,4]
r = np.array([[4,56,7]])

In [8]:
torch.tensor(l)

tensor([13,  4])

In [9]:
torch.tensor(r)

tensor([[ 4, 56,  7]])

In [10]:
x.size()

torch.Size([5, 4])

In [11]:
type(x)

torch.Tensor

In [12]:
x= torch.rand(2,2)
y= torch.rand(2,2)
print(x)
print(y)

tensor([[0.5835, 0.6168],
        [0.4354, 0.4381]])
tensor([[0.9110, 0.9923],
        [0.2372, 0.2473]])


In [13]:
x+y

tensor([[1.4944, 1.6092],
        [0.6725, 0.6854]])

In [14]:
torch.add(x,y)


tensor([[1.4944, 1.6092],
        [0.6725, 0.6854]])

In [15]:
y.add(x)

tensor([[1.4944, 1.6092],
        [0.6725, 0.6854]])

In [16]:
y

tensor([[0.9110, 0.9923],
        [0.2372, 0.2473]])

In [17]:
y.add_(x)

tensor([[1.4944, 1.6092],
        [0.6725, 0.6854]])

In [18]:
y

tensor([[1.4944, 1.6092],
        [0.6725, 0.6854]])

In [20]:
y[:,1]

tensor([1.6092, 0.6854])

In [22]:
y[1,:]

tensor([0.6725, 0.6854])

In [25]:
x = torch.rand(8,8)
print(x)
# 2차원 벡터 생성.. 랜덤으로

tensor([[0.5786, 0.1104, 0.3686, 0.7423, 0.1749, 0.7738, 0.1801, 0.4668],
        [0.6185, 0.8333, 0.3683, 0.4613, 0.5849, 0.4748, 0.5653, 0.6528],
        [0.5942, 0.8763, 0.3111, 0.9796, 0.8343, 0.8621, 0.7910, 0.8920],
        [0.7699, 0.8307, 0.1924, 0.4242, 0.6023, 0.5152, 0.3067, 0.8256],
        [0.4390, 0.6546, 0.1670, 0.4922, 0.9872, 0.4861, 0.3656, 0.8178],
        [0.7991, 0.2285, 0.7496, 0.0865, 0.5507, 0.4619, 0.3940, 0.9245],
        [0.1235, 0.0013, 0.8119, 0.5885, 0.1650, 0.2406, 0.3347, 0.9640],
        [0.1223, 0.4162, 0.3809, 0.8269, 0.0571, 0.3759, 0.1377, 0.5894]])


In [39]:
x.view(64) # CNN -> 플래튼 할때 사용
# 2차원 벡터를 1차원 벡터로 바꿈,

RuntimeError: ignored

In [27]:
x.view(4,16)
# 8x8 행렬을 --> 4x16 행렬로 바꿈

tensor([[0.5786, 0.1104, 0.3686, 0.7423, 0.1749, 0.7738, 0.1801, 0.4668, 0.6185,
         0.8333, 0.3683, 0.4613, 0.5849, 0.4748, 0.5653, 0.6528],
        [0.5942, 0.8763, 0.3111, 0.9796, 0.8343, 0.8621, 0.7910, 0.8920, 0.7699,
         0.8307, 0.1924, 0.4242, 0.6023, 0.5152, 0.3067, 0.8256],
        [0.4390, 0.6546, 0.1670, 0.4922, 0.9872, 0.4861, 0.3656, 0.8178, 0.7991,
         0.2285, 0.7496, 0.0865, 0.5507, 0.4619, 0.3940, 0.9245],
        [0.1235, 0.0013, 0.8119, 0.5885, 0.1650, 0.2406, 0.3347, 0.9640, 0.1223,
         0.4162, 0.3809, 0.8269, 0.0571, 0.3759, 0.1377, 0.5894]])

In [28]:
x.view(-1,16)
# 8x8 행렬을 --> 4x16 행렬로 바꿈

tensor([[0.5786, 0.1104, 0.3686, 0.7423, 0.1749, 0.7738, 0.1801, 0.4668, 0.6185,
         0.8333, 0.3683, 0.4613, 0.5849, 0.4748, 0.5653, 0.6528],
        [0.5942, 0.8763, 0.3111, 0.9796, 0.8343, 0.8621, 0.7910, 0.8920, 0.7699,
         0.8307, 0.1924, 0.4242, 0.6023, 0.5152, 0.3067, 0.8256],
        [0.4390, 0.6546, 0.1670, 0.4922, 0.9872, 0.4861, 0.3656, 0.8178, 0.7991,
         0.2285, 0.7496, 0.0865, 0.5507, 0.4619, 0.3940, 0.9245],
        [0.1235, 0.0013, 0.8119, 0.5885, 0.1650, 0.2406, 0.3347, 0.9640, 0.1223,
         0.4162, 0.3809, 0.8269, 0.0571, 0.3759, 0.1377, 0.5894]])

In [38]:
x.view(-1,4,4)
# 8x8 행렬을 --> 1x4x4 행렬로 바꿈


RuntimeError: ignored

In [32]:
# tensor를 numpy로 바꾸기
y = x.numpy()
print(y)
type(y)

[[0.5785806  0.11039889 0.36860567 0.74226135 0.17493308 0.7738229
  0.18008101 0.46682042]
 [0.618544   0.83331835 0.36834258 0.4613437  0.58490527 0.47483706
  0.5653389  0.6527528 ]
 [0.5942195  0.8762847  0.31108922 0.9796131  0.83426523 0.8621158
  0.79103583 0.8920354 ]
 [0.76985615 0.8307447  0.192424   0.42417675 0.6023475  0.515197
  0.30669713 0.82558537]
 [0.43901426 0.6545615  0.16700721 0.49223185 0.98715824 0.48605675
  0.36564296 0.8177814 ]
 [0.7990569  0.22849405 0.74961835 0.0865255  0.5506601  0.4618823
  0.39403474 0.9245208 ]
 [0.12353671 0.00128525 0.81187224 0.5884501  0.16499949 0.24059343
  0.3346951  0.96398073]
 [0.12232572 0.41619992 0.38094103 0.82689154 0.05707306 0.37590104
  0.13767505 0.5894211 ]]


numpy.ndarray

In [36]:
# item : 원소가 1개일때만 사용가능, 스칼라값 ==> loss 계산할때 대표 loss값을 직접뽑아내고 싶을때 사용하면 됨
x = torch.ones(1)

In [34]:
x

tensor([1.])

In [35]:
x.item()

1.0