<a href="https://colab.research.google.com/github/studian/study_pytorch/blob/main/2%EA%B0%95_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EC%9E%85%EB%AC%B8_%ED%95%84%EC%88%98_%EC%98%81%EC%83%81(%EC%97%AD%EC%A0%84%ED%8C%8C).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# 1. 변수 선언
x = torch.ones(2,2, requires_grad=True) # requires_grad=True : 역전파 가능하게 세팅, 즉 학습할때 업데이트 될수있도록..
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
# 2. 모델 내 연산 예측값 산출
y = x+1
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [4]:
# 3. 손실 함수 계산
z = 2*y**2 # 2*y^2
print(z)
res = z.mean()

tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)


In [5]:
# 4. 손실 산출
print(res)

tensor(8., grad_fn=<MeanBackward0>)


In [6]:
# 미분
# d(res) / dx_i = x_i + 1
#   res = (z_1 + ... + z4)/4
# z_i = 2 y_i ** 2
# z_i = 2 (x_i+1) ** 2
res.backward()

In [7]:
print(x.grad)

tensor([[2., 2.],
        [2., 2.]])


In [8]:
import torch.nn as nn
import torch.nn.functional as f # conv, 리니어함수, 활성함수 등이 있음